# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install -e .


env:
  global:
    # Doctr deploy key for matthewjohnpayne/mpc_boilerplate
    - secure: "hNzduCyZCBKkJosd8UWwdFY5KwDbblxF6puuv67XpCcDRRAqzzsKVztPe3pSMDJ4lTbf54EhPJ6lkfsXPszKTFcuek5Tfzmevd9nuXQBlWmCvHvaHfb7yILboBm8jYdVZjhSaZpmYZzSmYmsMVQLvKtQPCqVvQIFVjDAAqY8CxUWjihmboA3Qx+7eJofw7LWbN9Im9gstCUq/uSQMR6CWWg62sAAWQjj2Ihj2ajqMn+iA+XnGNSaOcxOnCyaNGhbCA6YwbXnUcHVfHzhxJlWZ0b/3IOl2NZYMAX/4zR7WP7OTOHZJ/+mfcib59nh+FdciTHPUciXzJt5RPrjKK+G1cXGMfGVN2oq5J8V6u8dglYolAV1YaejLQYD7+hUsFLJ50lylobVVAafXUM04lCs7ZrLUKc9NJjie0aHmGk+iOpA19lQUKbfHumGlECfjWFczSA0jCYuTGwH3EbSyjC1OTwP9dbC9niR4c+Oc274fnr9mTFaLLH2QkwQoN2fy60AS9yPBcKRt74liRjbiQ7MR+IbLtAv0p6Rsc0IASuD2QXagcfm/VlsNp2d3K7Kd/bM6fFUyfAWINS+5HWF11LD7xv5HkUwOrmVc/IhNEoEUpzjb6CJ/G9PoeTBIzik4avYX16uKQya/Gv+r2DOs4hSs+0Enb5M28X/V8yQC9GOaFc="

# Command to run tests, e.g. python setup.py test
script:
  # - pytest 
  - tox
  #- set -e
  #- make -C docs html  # Build the documentation. 
  #- pip install doctr
  #- doctr deploy --built-docs docs/_build/html .  # Publish the documentation. 



# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: matthewjohnpayne
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: matthewjohnpayne/mpc_boilerplate
    python: 3.6
